// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOVDh4_LVjxf1foh250Y6bQT515L-bjzk',
    appId: '1:337327696750:web:4e1a30ee730e96a588af7f',
    messagingSenderId: '337327696750',
    projectId: 'cook-guru-f9a8c',
    authDomain: 'cook-guru-f9a8c.firebaseapp.com',
    storageBucket: 'cook-guru-f9a8c.appspot.com',
    measurementId: 'G-SVYH1MJ995',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmtLek6DyRDjh6JTG8IF-x6PzqHBlZW2Q',
    appId: '1:337327696750:android:92f451000bc9f67e88af7f',
    messagingSenderId: '337327696750',
    projectId: 'cook-guru-f9a8c',
    storageBucket: 'cook-guru-f9a8c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcFDEdBNdFYaGEa7_9FUrE-ak6gaMQJVU',
    appId: '1:337327696750:ios:77012317c84c372088af7f',
    messagingSenderId: '337327696750',
    projectId: 'cook-guru-f9a8c',
    storageBucket: 'cook-guru-f9a8c.appspot.com',
    iosBundleId: 'com.cookguru.cookGuru',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcFDEdBNdFYaGEa7_9FUrE-ak6gaMQJVU',
    appId: '1:337327696750:ios:77012317c84c372088af7f',
    messagingSenderId: '337327696750',
    projectId: 'cook-guru-f9a8c',
    storageBucket: 'cook-guru-f9a8c.appspot.com',
    iosBundleId: 'com.cookguru.cookGuru',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOVDh4_LVjxf1foh250Y6bQT515L-bjzk',
    appId: '1:337327696750:web:86266d1df258e70988af7f',
    messagingSenderId: '337327696750',
    projectId: 'cook-guru-f9a8c',
    authDomain: 'cook-guru-f9a8c.firebaseapp.com',
    storageBucket: 'cook-guru-f9a8c.appspot.com',
    measurementId: 'G-YFVVN61PP5',
  );
}
